# Generated by Django 2.0.2 on 2018-02-08 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ictc_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ictc_site.Contact'),
        ),
    ]
